# Generated by Django 5.2.6 on 2025-09-13 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('kits_jerseys', 'Kits & Jerseys'), ('footwear', 'Footwear'), ('equipment', 'Equipment'), ('goalkeeper', 'Goalkeeper'), ('clothing', 'Clothing & Apparel'), ('fan_shop', 'Fan Shop'), ('kids_youth', 'Kids & Youth'), ('accessories', 'Accessories')], default='equipment', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
